# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test on Python 3.4

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.4.10
    - name: Install dependencies
      run: |
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --exclude=aioax25/aiosupport/py35.py,tests/test_aiosupport/py35.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --exclude=aioax25/aiosupport/py35.py,tests/test_aiosupport/py35.py --count --exit-zero --max-complexity=10 --statistics
    - name: Test with py.test (no coverage)
      run: |
        python -m pytest
